apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      ports:
        - protocol: TCP
          port: 8888
          targetPort: 8888
      containers:
      - name: main
        image: wil42/playground:v2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8888
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  type: LoadBalancer
  selector:
    app: app1
